name:                tinka-hs
version:             0.1.0.0
github:              "atennapel/tinka-hs"
license:             BSD3
author:              "Albert ten Napel"
maintainer:          "aptennap@gmail.com"
copyright:           "2021 Albert ten Napel"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/atennapel/tinka-hs#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- transformers
- containers

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches
- -Wno-missing-pattern-synonym-signatures

default-extensions:
- DerivingVia
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DataKinds
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- PatternSynonyms
- StandaloneDeriving
- Strict
- TupleSections
- ViewPatterns
- BlockArguments
- GADTs

source-dirs: src

executable:
  main: Main.hs
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -O
